version: "3.2"
services:
  # C++ tracing example program
  tracer:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
        - 'dd-agent'

  # latest Datadog agent
  dd-agent:
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/proc/:/host/proc/:ro'
      - '/sys/fs/cgroup/:/host/sys/fs/cgroup:ro'
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
    image: 'datadog/agent'
